Make git-flow-version a first-class citizen amongst the other subcommands.

diff --git a/bump-version b/bump-version
--- a/bump-version
+++ b/bump-version
@@ -8,6 +8,11 @@ if [ $# -ne 1 ]; then
 	exit 1
 fi
 
-echo "GITFLOW_VERSION=$1" > git-flow-version
+if ! sed 's/^GITFLOW_VERSION=.*$/GITFLOW_VERSION='$1'/g' git-flow-version > .git-flow-version.new; then
+	echo "Could not replace GITFLOW_VERSION variable." >&2
+	exit 2
+fi
+
+mv .git-flow-version.new git-flow-version
 git add git-flow-version
 git commit -m "Bumped version number to $1" git-flow-version
