Added new experimental `feature pull` subcommand.
This new subcommand lets you easily work together with peers on features. It's
intended to be extremely simple to pull changes from your co-developers.

This implementation may also be ported to release and/or hotfix branches in the
near future, if we agree on the final implementation details.

Example use
===========
Sharing development of feature branches goes as follows:

Suppose Alice and Bob are both developers on project Foo.  They have local
repos that are up-to-date with `origin`.  Then, Alice starts working on some
feature:

   alice$ git flow feature start newprotocol
   Switched to a new branch 'feature/newprotocol'
   ...

Then, she hacks on the new feature, commits as desired, until the feature's
finished.  She then likes Bob to code-review the feature, so she asks Bob to
pull from her.  (Assuming Bob has a Git remote defined, pointing to Alice's
repo.)

    bob$ git remote
    alice

    bob$ git branch
    * develop
      feature/reader
      master

    bob$ git flow feature pull alice newprotocol
    Created local branch feature/newprotocol based on alice's feature/newprotocol.

    bob$ git branch
      develop
    * feature/newprotocol
      feature/reader
      master

Since the new feature branch is already checked out, Bob can immediately start
peer reviewing the code.  He changes the code as desired and commits each
comment individually, so Alice can later read the Git commit log as the peer
review log.

    bob$ git commit
    [feature/newprotocol 1f6fa95] Forgot return statement.
     1 files changed, 1 insertions(+), 1 deletions(-)
    ...

When he's finished, he tells Alice he's done.  Alice then, in turn pulls in the
peer review commits from Bob, using the same command Bob used to fetch the
changes initially.  (Because feature/newprotocol is still her current branch,
she may omit the explicit 'newprotocols' argument.)

    alice$ git flow feature pull bob
    Pulled bob's changes into feature/newprotocol.

If she disagrees with Bob's comments, she may again commit changes and ask Bob
to do the same again.  This leads to a continuous pull cycle until both parties
agree on the final implementation.  Then, Alice (as the feature owner) finished
the feature.  Bob may discard his feature branch.

diff --git a/git-flow-feature b/git-flow-feature
--- a/git-flow-feature
+++ b/git-flow-feature
@@ -50,6 +50,7 @@ usage() {
 	echo "       git flow feature diff [<name|nameprefix>]"
 	echo "       git flow feature rebase [-i] [<name|nameprefix>]"
 	echo "       git flow feature checkout [<name|nameprefix>]"
+	echo "       git flow feature pull <remote> [<name>]"
 }
 
 cmd_default() {
@@ -142,31 +143,53 @@ expand_nameprefix_arg() {
 	esac
 }
 
+use_current_feature_branch_name() {
+	local current_branch=$(git_current_branch)
+	if startswith "$current_branch" "$PREFIX"; then
+		BRANCH=$current_branch
+		NAME=${BRANCH#$PREFIX}
+	else
+		warn "The current HEAD is no feature branch."
+		warn "Please specify a <name> argument."
+		exit 1
+	fi
+}
+
 expand_nameprefix_arg_or_current() {
 	if [ "$NAME" != "" ]; then
 		expand_nameprefix_arg
 		require_branch "$PREFIX$NAME"
 	else
-		local current_branch=$(git_current_branch)
-		if startswith "$current_branch" "$PREFIX"; then
-			BRANCH=$current_branch
-			NAME=${BRANCH#$PREFIX}
-		else
-			warn "The current HEAD is no feature branch."
-			warn "To diff a feature, specify a <name> argument."
-			usage
-			exit 1
-		fi
+		use_current_feature_branch_name
 	fi
 }
 
-parse_args() {
+name_or_current() {
+	if [ -z "$NAME" ]; then
+		use_current_feature_branch_name
+	fi
+}
+
+parse_cmdline() {
 	# parse options
 	FLAGS "$@" || exit $?
 	eval set -- "${FLAGS_ARGV}"
+}
+
+parse_args() {
+	parse_cmdline "$@"
 
 	# read arguments into global variables
 	NAME=$1
+	BRANCH=$PREFIX$NAME
+}
+
+parse_remote_name() {
+	parse_cmdline "$@"
+
+	# read arguments into global variables
+	REMOTE=$1
+	NAME=$2
 	BRANCH=$PREFIX$NAME
 }
 
@@ -421,4 +444,52 @@ cmd_rebase() {
 		OPTS="$OPTS -i"
 	fi
 	git rebase $OPTS "$DEVELOP_BRANCH"
+}
+
+avoid_accidental_cross_branch_action() {
+	local current_branch=$(git_current_branch)
+	if [ "$BRANCH" != "$current_branch" ]; then
+		warn "Trying to pull from '$BRANCH' while currently on branch '$current_branch'."
+		warn "To avoid unintended merges, git-flow aborted."
+		return 1
+	fi
+	return 0
+}
+
+cmd_pull() {
+	#DEFINE_string prefix false 'alternative remote feature branch name prefix' p
+	parse_remote_name "$@"
+
+	if [ -z "$REMOTE" ]; then
+		die "Name a remote explicitly."
+	fi
+	name_or_current
+
+	# To avoid accidentally merging different feature branches into each other,
+	# die if the current feature branch differs from the requested $NAME
+	# argument.
+	local current_branch=$(git_current_branch)
+	if startswith "$current_branch" "$PREFIX"; then
+		# we are on a local feature branch already, so $BRANCH must be equal to
+		# the current branch
+		avoid_accidental_cross_branch_action || die
+	fi
+
+	require_clean_working_tree
+
+	if git_branch_exists "$BRANCH"; then
+		# Again, avoid accidental merges
+		avoid_accidental_cross_branch_action || die
+
+		# we already have a local branch called like this, so simply pull the
+		# remote changes in
+		git pull -q "$REMOTE" "$BRANCH" || die "Failed to pull from remote '$REMOTE'."
+		echo "Pulled $REMOTE's changes into $BRANCH."
+	else
+		# setup the local branch clone for the first time
+		git fetch -q "$REMOTE" "$BRANCH" || die "Fetch failed."     # stores in FETCH_HEAD
+		git branch --no-track "$BRANCH" FETCH_HEAD || die "Branch failed."
+		git checkout -q "$BRANCH" || die "Checking out new local branch failed."
+		echo "Created local branch $BRANCH based on $REMOTE's $BRANCH."
+	fi
 }
