Die when branch can't be created in action start

diff --git a/git-flow-feature b/git-flow-feature
--- a/git-flow-feature
+++ b/git-flow-feature
@@ -211,9 +211,7 @@ cmd_start() {
 	run_pre_hook "$NAME" "$ORIGIN" "$BRANCH" "$BASE"
 
 	# create branch
-	if ! git checkout -b "$BRANCH" "$BASE"; then
-		die "Could not create feature branch '$BRANCH'"
-	fi
+	git checkout -b "$BRANCH" "$BASE" || die "Could not create feature branch '$BRANCH'"
 
 	run_post_hook "$NAME" "$ORIGIN" "$BRANCH" "$BASE"
 
diff --git a/git-flow-support b/git-flow-support
--- a/git-flow-support
+++ b/git-flow-support
@@ -168,7 +168,7 @@ cmd_start() {
 	require_branch_absent "$BRANCH"
 
 	# Create branch
-	git checkout -b "$BRANCH" "$BASE"
+	git checkout -b "$BRANCH" "$BASE" || die "Could not create support branch '$BRANCH'"
 
 	echo
 	echo "Summary of actions:"
