add a option for remote repository

diff --git a/git-flow-feature b/git-flow-feature
--- a/git-flow-feature
+++ b/git-flow-feature
@@ -43,8 +43,8 @@ PREFIX=$(git config --get gitflow.prefix.feature)
 
 usage() {
 	echo "usage: git flow feature [list] [-v]"
-	echo "       git flow feature start [-F] <name> [<base>]"
-	echo "       git flow feature finish [-rFk] [<name|nameprefix>]"
+	echo "       git flow feature start [-F|-R] <name> [<base>]"
+	echo "       git flow feature finish [-rFk|-R] [<name|nameprefix>]"
 	echo "       git flow feature publish <name>"
 	echo "       git flow feature track <name>"
 	echo "       git flow feature diff [<name|nameprefix>]"
@@ -193,6 +193,7 @@ parse_remote_name() {
 
 cmd_start() {
 	DEFINE_boolean fetch false 'fetch from origin before performing local operation' F
+  DEFINE_boolean remote false "make and push remote branch to $ORIGIN" R
 	parse_args "$@"
 	BASE=${2:-$DEVELOP_BRANCH}
 	require_name_arg
@@ -205,6 +206,13 @@ cmd_start() {
 		git fetch -q "$ORIGIN" "$DEVELOP_BRANCH"
 	fi
 
+	if flag remote; then
+		git fetch -q "$ORIGIN" "$DEVELOP_BRANCH"
+    if has "$ORIGIN/$BRANCH" $(git_remote_branches); then
+      die "$BRANCH has already existed at $ORIGIN"
+    fi
+	fi
+
 	# if the origin branch counterpart exists, assert that the local branch
 	# isn't behind it (to avoid unnecessary rebasing)
 	if git_branch_exists "$ORIGIN/$DEVELOP_BRANCH"; then
@@ -215,6 +223,12 @@ cmd_start() {
 	if ! git checkout -b "$BRANCH" "$BASE"; then
 		die "Could not create feature branch '$BRANCH'"
 	fi
+	# create remote branch
+  if flag remote; then
+    if ! git push --set-upstream "$ORIGIN" "$BRANCH"; then
+      die "Could not create remote branch '$BRANCH' at '$ORIGIN'"
+    fi
+  fi
 
 	echo
 	echo "Summary of actions:"
@@ -229,6 +243,7 @@ cmd_start() {
 
 cmd_finish() {
 	DEFINE_boolean fetch false "fetch from $ORIGIN before performing finish" F
+  DEFINE_boolean remote false "push the develop branch to remote and remove a remote feature branch at $ORIGIN" R
 	DEFINE_boolean rebase false "rebase instead of merge" r
 	DEFINE_boolean keep false "keep branch after performing finish" k
 	parse_args "$@"
@@ -282,10 +297,12 @@ cmd_finish() {
 
 	# update local repo with remote changes first, if asked
 	if has "$ORIGIN/$BRANCH" $(git_remote_branches); then
-		if flag fetch; then
+		if flag fetch -o flag remote; then
 			git fetch -q "$ORIGIN" "$BRANCH"
 			git fetch -q "$ORIGIN" "$DEVELOP_BRANCH"
 		fi
+  elif flag remote; then
+    die "not exist the remote $BRANCH branch at $ORIGIN"
 	fi
 
 	if has "$ORIGIN/$BRANCH" $(git_remote_branches); then
@@ -343,7 +360,10 @@ helper_finish_cleanup() {
 	if flag fetch; then
 		git push "$ORIGIN" ":refs/heads/$BRANCH"
 	fi
-	
+	if flag remote; then
+		git push "$ORIGIN" ":$BRANCH"
+    git push "$ORIGIN" "$DEVELOP_BRANCH"
+	fi
 	
 	if noflag keep; then
 		git branch -d "$BRANCH"
diff --git a/git-flow-release b/git-flow-release
--- a/git-flow-release
+++ b/git-flow-release
@@ -44,8 +44,8 @@ PREFIX=$(git config --get gitflow.prefix.release)
 
 usage() {
 	echo "usage: git flow release [list] [-v]"
-	echo "       git flow release start [-F] <version> [<base>]"
-	echo "       git flow release finish [-Fsumpk] <version>"
+	echo "       git flow release start [-F|-R] <version> [<base>]"
+	echo "       git flow release finish [-Fsumpk|-R] <version>"
 	echo "       git flow release publish <name>"
 	echo "       git flow release track <name>"
 }
@@ -151,6 +151,7 @@ require_no_existing_release_branches() {
 
 cmd_start() {
 	DEFINE_boolean fetch false "fetch from $ORIGIN before performing finish" F
+  DEFINE_boolean remote false "make and push remote branch to $ORIGIN" R
 	parse_args "$@"
 	BASE=${2:-$DEVELOP_BRANCH}
 	require_version_arg
@@ -164,12 +165,26 @@ cmd_start() {
 	if flag fetch; then
 		git fetch -q "$ORIGIN" "$DEVELOP_BRANCH"
 	fi
+
+	if flag remote; then
+		git fetch -q "$ORIGIN" "$DEVELOP_BRANCH"
+    if has "$ORIGIN/$BRANCH" $(git_remote_branches); then
+      die "$BRANCH has already existed at $ORIGIN"
+    fi
+	fi
+
 	if has "$ORIGIN/$DEVELOP_BRANCH" $(git_remote_branches); then
 		require_branches_equal "$DEVELOP_BRANCH" "$ORIGIN/$DEVELOP_BRANCH"
 	fi
 
 	# create branch
 	git checkout -b "$BRANCH" "$BASE"
+	# create remote branch
+  if flag remote; then
+    if ! git push --set-upstream "$ORIGIN" "$BRANCH"; then
+      die "Could not create remote branch '$BRANCH' at '$ORIGIN'"
+    fi
+  fi
 
 	echo
 	echo "Summary of actions:"
@@ -187,6 +202,7 @@ cmd_start() {
 
 cmd_finish() {
 	DEFINE_boolean fetch false "fetch from $ORIGIN before performing finish" F
+  DEFINE_boolean remote false "push the master/develop to remote and remove a remote hotfix branch at $ORIGIN" R
 	DEFINE_boolean sign false "sign the release tag cryptographically" s
 	DEFINE_string signingkey "" "use the given GPG-key for the digital signature (implies -s)" u
 	DEFINE_string message "" "use the given tag message" m
@@ -205,7 +221,7 @@ cmd_finish() {
 	# sanity checks
 	require_branch "$BRANCH"
 	require_clean_working_tree
-	if flag fetch; then
+	if flag fetch -o flag remote; then
 		git fetch -q "$ORIGIN" "$MASTER_BRANCH" || \
 		  die "Could not fetch $MASTER_BRANCH from $ORIGIN."
 		git fetch -q "$ORIGIN" "$DEVELOP_BRANCH" || \
@@ -217,6 +233,9 @@ cmd_finish() {
 	if has "$ORIGIN/$DEVELOP_BRANCH" $(git_remote_branches); then
 		require_branches_equal "$DEVELOP_BRANCH" "$ORIGIN/$DEVELOP_BRANCH"
 	fi
+  if flag remote -a ! has "$ORIGIN/$BRANCH" $(git_remote_branches); then
+    die "not exist the remote $BRANCH branch at $ORIGIN"
+  fi
 
 	# try to merge into master
 	# in case a previous attempt to finish this release branch has failed,
@@ -266,7 +285,7 @@ cmd_finish() {
 		git branch -d "$BRANCH"
 	fi
 
-	if flag push; then
+	if flag push -o flag remote; then
 		git push "$ORIGIN" "$DEVELOP_BRANCH" || \
 			die "Could not push to $DEVELOP_BRANCH from $ORIGIN."
 		git push "$ORIGIN" "$MASTER_BRANCH" || \
