Commentary updates.

diff --git a/git-flow-feature b/git-flow-feature
--- a/git-flow-feature
+++ b/git-flow-feature
@@ -2,8 +2,8 @@
 # git-flow -- A collection of Git extensions to provide high-level
 # repository operations for Vincent Driessen's branching model.
 #
-# Original blog post presenting this model is found at:
-#    http://nvie.com/git-model
+# A blog post presenting this model is found at:
+#    http://blog.avirtualhome.com/development-workflow-using-git/
 #
 # Feel free to contribute to this project at:
 #    http://github.com/petervanderdoes/gitflow
@@ -76,7 +76,7 @@ cmd_list() {
 	current_branch=$(git branch --no-color | grep '^\* ' | grep -v 'no branch' | sed 's/^* //g')
 	short_names=$(echo "$feature_branches" | sed "s ^$PREFIX  g")
 
-	# determine column width first
+	# Determine column width first
 	local width=0
 	local branch
 	for branch in $short_names; do
@@ -196,15 +196,15 @@ cmd_start() {
 	BASE=${2:-$DEVELOP_BRANCH}
 	require_name_arg
 
-	# sanity checks
+	# Sanity checks
 	require_branch_absent "$BRANCH"
 
-	# update the local repo with remote changes, if asked
+	# Update the local repo with remote changes, if asked
 	if flag fetch; then
 		git fetch -q "$ORIGIN" "$DEVELOP_BRANCH"
 	fi
 
-	# if the origin branch counterpart exists, assert that the local branch
+	# If the origin branch counterpart exists, assert that the local branch
 	# isn't behind it (to avoid unnecessary rebasing)
 	if git_branch_exists "$ORIGIN/$DEVELOP_BRANCH"; then
 		require_branches_equal "$DEVELOP_BRANCH" "$ORIGIN/$DEVELOP_BRANCH"
@@ -238,10 +238,10 @@ cmd_finish() {
 	parse_args "$@"
 	expand_nameprefix_arg_or_current
 
-	# sanity checks
+	# Sanity checks
 	require_branch "$BRANCH"
 
-	# detect if we're restoring from a merge conflict
+	# Detect if we're restoring from a merge conflict
 	if [ -f "$DOT_GIT_DIR/.gitflow/MERGE_BASE" ]; then
 		#
 		# TODO: detect that we're working on the correct branch here!
@@ -263,9 +263,10 @@ cmd_finish() {
 				helper_finish_cleanup
 				exit 0
 			else
-				# If the user cancelled the merge and decided to wait until later,
-				# that's fine. But we have to acknowledge this by removing the
-				# MERGE_BASE file and continuing normal execution of the finish
+				# If the user cancelled the merge and decided to wait until
+ 	 	 	 	# later,that's fine. But we have to acknowledge this by
+				# removing the MERGE_BASE file and continuing normal execution
+				# of the finish
 				rm -f "$DOT_GIT_DIR/.gitflow/MERGE_BASE"
 			fi
 		else
@@ -281,10 +282,10 @@ cmd_finish() {
 		fi
 	fi
 
-	# sanity checks
+	# Sanity checks
 	require_clean_working_tree
 
-	# update local repo with remote changes first, if asked
+	# Update local repo with remote changes first, if asked
 	if has "$ORIGIN/$BRANCH" $(git_remote_branches); then
 		if flag fetch; then
 			git fetch -q "$ORIGIN" "$BRANCH"
@@ -301,7 +302,7 @@ cmd_finish() {
 
     run_pre_hook "$NAME" "$ORIGIN" "$BRANCH"
 
-	# if the user wants to rebase, do that first
+	# If the user wants to rebase, do that first
 	if flag rebase; then
 		if ! git flow feature rebase "$NAME" "$DEVELOP_BRANCH"; then
 			warn "Finish was aborted due to conflicts during rebase."
@@ -312,7 +313,7 @@ cmd_finish() {
 		fi
 	fi
 
-	# merge into BASE
+	# Merge into BASE
 	git checkout "$DEVELOP_BRANCH"
 	if [ "$(git rev-list -n2 "$DEVELOP_BRANCH..$BRANCH" | wc -l)" -eq 1 ]; then
 		git merge --ff "$BRANCH"
@@ -321,8 +322,9 @@ cmd_finish() {
 	fi
 
 	if [ $? -ne 0 ]; then
-		# oops.. we have a merge conflict!
-		# write the given $DEVELOP_BRANCH to a temporary file (we need it later)
+		# Oops.. we have a merge conflict!
+		# Write the given $DEVELOP_BRANCH to a temporary file as we will
+		# be needing it later.
 		mkdir -p "$DOT_GIT_DIR/.gitflow"
 		echo "$DEVELOP_BRANCH" > "$DOT_GIT_DIR/.gitflow/MERGE_BASE"
 		echo
@@ -338,16 +340,16 @@ cmd_finish() {
 
     run_post_hook "$NAME" "$ORIGIN" "$BRANCH"
 
-	# when no merge conflict is detected, just clean up the feature branch
+	# When no merge conflict is detected, just clean up the feature branch
 	helper_finish_cleanup
 }
 
 helper_finish_cleanup() {
-	# sanity checks
+	# Sanity checks
 	require_branch "$BRANCH"
 	require_clean_working_tree
 
-	# delete branch
+	# Delete branch
 	if flag fetch; then
 		git push "$ORIGIN" ":refs/heads/$BRANCH"
 	fi
@@ -378,7 +380,7 @@ cmd_publish() {
 	parse_args "$@"
 	expand_nameprefix_arg
 
-	# sanity checks
+	# Sanity checks
 	require_clean_working_tree
 	require_branch "$BRANCH"
 	git fetch -q "$ORIGIN"
@@ -386,11 +388,11 @@ cmd_publish() {
 
 	run_pre_hook "$NAME" "$ORIGIN" "$BRANCH"
 
-	# create remote branch
+	# Create remote branch
 	git push "$ORIGIN" "$BRANCH:refs/heads/$BRANCH"
 	git fetch -q "$ORIGIN"
 
-	# configure remote tracking
+	# Configure remote tracking
 	git config "branch.$BRANCH.remote" "$ORIGIN"
 	git config "branch.$BRANCH.merge" "refs/heads/$BRANCH"
 	git checkout "$BRANCH"
@@ -409,7 +411,7 @@ cmd_track() {
 	parse_args "$@"
 	require_name_arg
 
-	# sanity checks
+	# Sanity checks
 	require_clean_working_tree
 	require_branch_absent "$BRANCH"
 
@@ -418,7 +420,7 @@ cmd_track() {
 	git fetch -q "$ORIGIN"
 	require_branch "$ORIGIN/$BRANCH"
 
-	# create tracking branch
+	# Create tracking branch
 	git checkout -b "$BRANCH" "$ORIGIN/$BRANCH"
 
 	run_post_hook "$NAME" "$ORIGIN" "$BRANCH"
@@ -504,7 +506,7 @@ cmd_pull() {
 	# argument.
 	local current_branch=$(git_current_branch)
 	if startswith "$current_branch" "$PREFIX"; then
-		# we are on a local feature branch already, so $BRANCH must be equal to
+		# We are on a local feature branch already, so $BRANCH must be equal to
 		# the current branch
 		avoid_accidental_cross_branch_action || die
 	fi
@@ -517,7 +519,7 @@ cmd_pull() {
 		# Again, avoid accidental merges
 		avoid_accidental_cross_branch_action || die
 
-		# we already have a local branch called like this, so simply pull the
+		# We already have a local branch called like this, so simply pull the
 		# remote changes in
 		if flag rebase; then
 			if ! git pull --rebase -q "$REMOTE" "$BRANCH"; then
@@ -530,8 +532,8 @@ cmd_pull() {
 
 		echo "Pulled $REMOTE's changes into $BRANCH."
 	else
-		# setup the local branch clone for the first time
-		git fetch -q "$REMOTE" "$BRANCH" || die "Fetch failed."     # stores in FETCH_HEAD
+		# Setup the local branch clone for the first time
+		git fetch -q "$REMOTE" "$BRANCH" || die "Fetch failed."     # Stores in FETCH_HEAD
 		git branch --no-track "$BRANCH" FETCH_HEAD || die "Branch failed."
 		git checkout -q "$BRANCH" || die "Checking out new local branch failed."
 		echo "Created local branch $BRANCH based on $REMOTE's $BRANCH."
