Give all subcommands an optional setup() function that will be called by git-flow in order to let the subcommand initialize its environment.
Give all the branch-type subcommands a default explicit "list" action, too.

Order the functions inside each of the subcommands in a specific order, for consistency:
- usage()
- setup()
- cmd_default()
- cmd_list()
- cmd_help()
- parse_args()
- other commands

diff --git a/git-flow-feature b/git-flow-feature
--- a/git-flow-feature
+++ b/git-flow-feature
@@ -13,7 +13,7 @@
 #
 
 usage() {
-	echo "usage: git flow feature"
+	echo "usage: git flow feature [list]"
 	echo "       git flow feature start <name> [<base>]"
 	echo "       git flow feature finish <name> [<base>]"
 	echo "       git flow feature publish <name>"
@@ -34,21 +34,16 @@ usage() {
 	#echo "--push      Push to the origin repo when finished"
 }
 
-parse_args() {
-	NAME="$1"
-	BASE="${2:-$DEVELOP_BRANCH}"
-	if [ "$NAME" = "" ]; then
-		echo "Missing argument <name>."
-		usage
-		exit 1
-	fi
+# setup will always be called before the actual cmd_* functions
+setup() {
 	PREFIX=$(git config --get gitflow.prefix.feature || echo feature/)
-	BRANCH=$PREFIX$NAME
 }
 
 cmd_default() {
-	# TODO: Refactor getting this prefix into a general function
-	PREFIX=$(git config --get gitflow.prefix.feature || echo feature/)
+	cmd_list "$@"
+}
+
+cmd_list() {
 	FEATURE_BRANCHES="$(echo "$LOCAL_BRANCHES" | grep "^$PREFIX")"
 	if [ -z "$FEATURE_BRANCHES" ]; then
 		warn "No feature branches exist."
@@ -60,6 +55,18 @@ cmd_default() {
 cmd_help() {
 	usage
 	exit 0
+}
+
+parse_args() {
+	NAME="$1"
+	BASE="${2:-$DEVELOP_BRANCH}"
+	if [ "$NAME" = "" ]; then
+		echo "Missing argument <name>."
+		usage
+		exit 1
+	fi
+	PREFIX=$(git config --get gitflow.prefix.feature || echo feature/)
+	BRANCH=$PREFIX$NAME
 }
 
 cmd_start() {
diff --git a/git-flow-hotfix b/git-flow-hotfix
--- a/git-flow-hotfix
+++ b/git-flow-hotfix
@@ -13,7 +13,7 @@
 #
 
 usage() {
-	echo "usage: git flow hotfix"
+	echo "usage: git flow hotfix [list]"
 	echo "       git flow hotfix start <version> [<base>]"
 	echo "       git flow hotfix finish <version> [<base>]"
 	# TODO
@@ -28,21 +28,16 @@ usage() {
 	#echo "--push      Push to the origin repo when finished"
 }
 
-parse_args() {
-	VERSION="$1"
-	BASE="${2:-$MASTER_BRANCH}"
-	if [ "$VERSION" = "" ]; then
-		echo "Missing argument <version>."
-		usage
-		exit 1
-	fi
+# setup will always be called before the actual cmd_* functions
+setup() {
 	PREFIX=$(git config --get gitflow.prefix.hotfix || echo hotfix/)
-	BRANCH=$PREFIX$VERSION
 }
 
 cmd_default() {
-	# TODO: Refactor getting this prefix into a general function
-	PREFIX=$(git config --get gitflow.prefix.hotfix || echo hotfix/)
+	cmd_list "$@"
+}
+
+cmd_list() {
 	HOTFIX_BRANCHES="$(echo "$LOCAL_BRANCHES" | grep "^$PREFIX")"
 	if [ -z "$HOTFIX_BRANCHES" ]; then
 		warn "No hotfix branches exist."
@@ -54,6 +49,18 @@ cmd_default() {
 cmd_help() {
 	usage
 	exit 0
+}
+
+parse_args() {
+	VERSION="$1"
+	BASE="${2:-$MASTER_BRANCH}"
+	if [ "$VERSION" = "" ]; then
+		echo "Missing argument <version>."
+		usage
+		exit 1
+	fi
+	PREFIX=$(git config --get gitflow.prefix.hotfix || echo hotfix/)
+	BRANCH=$PREFIX$VERSION
 }
 
 cmd_start() {
diff --git a/git-flow-release b/git-flow-release
--- a/git-flow-release
+++ b/git-flow-release
@@ -13,7 +13,7 @@
 #
 
 usage() {
-	echo "usage: git flow release"
+	echo "usage: git flow release [list]"
 	echo "       git flow release start <version>"
 	echo "       git flow release finish <version>"
 	# TODO
@@ -29,21 +29,17 @@ usage() {
 	#echo "--push      Push to the origin repo when finished"
 }
 
-parse_args() {
-	VERSION_PREFIX=$(git config --get gitflow.prefix.versiontag)
-	VERSION="$1"
-	if [ "$VERSION" = "" ]; then
-		echo "Missing argument <version>."
-		usage
-		exit 1
-	fi
+# setup will always be called before the actual cmd_* functions
+setup() {
 	PREFIX=$(git config --get gitflow.prefix.release || echo release/)
-	BRANCH=$PREFIX$VERSION
+	VERSION_PREFIX=$(git config --get gitflow.prefix.versiontag)
 }
 
 cmd_default() {
-	# TODO: Refactor getting this prefix into a general function
-	PREFIX=$(git config --get gitflow.prefix.release || echo release/)
+	cmd_list "$@"
+}
+
+cmd_list() {
 	RELEASE_BRANCHES="$(echo "$LOCAL_BRANCHES" | grep "^$PREFIX")"
 	if [ -z "$RELEASE_BRANCHES" ]; then
 		warn "No release branches exist."
@@ -55,6 +51,16 @@ cmd_default() {
 cmd_help() {
 	usage
 	exit 0
+}
+
+parse_args() {
+	VERSION="$1"
+	if [ "$VERSION" = "" ]; then
+		echo "Missing argument <version>."
+		usage
+		exit 1
+	fi
+	BRANCH=$PREFIX$VERSION
 }
 
 cmd_start() {
