Merging more of the feaeture commands into issue.
- This mimics less of a hotfix and more of a feature. There's still some tweaking but
basically should work very similar now.

diff --git a/git-flow-issue b/git-flow-issue
--- a/git-flow-issue
+++ b/git-flow-issue
@@ -44,13 +44,12 @@ init() {
 }
 
 usage() {
-    echo <<EOF
-usage: git flow issue [list] 
-       git flow issue start -F <name> [<base>]
-       git flow issue finish [<name|nameprefix>]
-       git flow issue publish <name>
-       git flow issue track <name>
-EOF
+    echo "usage: git flow issue [list] [-v]"
+    echo "       git flow issue start -F <name> [<base>]"
+    echo "       git flow issue finish [-FkDS] [<name|nameprefix>]"
+    echo "       git flow issue publish <name>"
+    echo "       git flow issue track <name>"
+    echo "       git flow issue pull [-r] <remote> [<name>]"
 }
 
 cmd_default() {
@@ -70,7 +69,7 @@ cmd_list() {
         warn ""
         warn "You can start a new issue branch:"
         warn ""
-        warn "    git flow issue start <version> [<base>]"
+        warn "    git flow issue start <name> [<base>]"
         warn ""
 	exit 0
     fi
@@ -85,12 +84,12 @@ cmd_list() {
 	width=$(max $width $len)
     done
     width=$(($width+3))
-    
+
     local branch
     for branch in $short_names; do
 	local fullname=$PREFIX$branch
-	local base=$(git merge-base "$fullname" "$MASTER_BRANCH")
-	local master_sha=$(git rev-parse "$MASTER_BRANCH")
+	local base=$(git merge-base "$fullname" "$DEVELOP_BRANCH")
+	local develop_sha=$(git rev-parse "$DEVELOP_BRANCH")
 	local branch_sha=$(git rev-parse "$fullname")
 	if [ "$fullname" = "$current_branch" ]; then
 	    printf "* "
@@ -99,7 +98,7 @@ cmd_list() {
 	fi
 	if flag verbose; then
 	    printf "%-${width}s" "$branch"
-	    if [ "$branch_sha" = "$master_sha" ]; then
+	    if [ "$branch_sha" = "$develop_sha" ]; then
 		printf "(no commits yet)"
 	    else
 		local tagname=$(git name-rev --tags --no-undefined --name-only "$base")
@@ -129,73 +128,96 @@ parse_args() {
     eval set -- "${FLAGS_ARGV}"
     
     # read arguments into global variables
-    VERSION=$1
-    BRANCH=$PREFIX$VERSION
+    NAME=$1
+    BRANCH=$PREFIX$NAME
 }
 
-require_version_arg() {
-    if [ "$VERSION" = "" ]; then
-	warn "Missing argument <version>"
+parse_remote_name() {
+    # parse options
+    FLAGS "$@" || exit $?
+    eval set -- "${FLAGS_ARGV}"
+
+    # read arguments into global variables
+    REMOTE=$1
+    NAME=$2
+    BRANCH=$PREFIX$NAME
+}
+
+require_name_arg() {
+    if [ "$NAME" = "" ]; then
+	warn "Missing argument <name>"
 	usage
 	exit 1
     fi
 }
 
-require_base_is_on_master() {
-    if ! git branch --no-color --contains "$BASE" 2>/dev/null \
-	| sed 's/[* ] //g' \
-	| grep -q "^$MASTER_BRANCH\$"; then
-	die "fatal: Given base '$BASE' is not a valid commit on '$MASTER_BRANCH'."
-    fi
+expand_nameprefix_arg() {
+    require_name_arg
+
+    local expanded_name
+    local exitcode
+    expanded_name=$(gitflow_resolve_nameprefix "$NAME" "$PREFIX")
+    exitcode=$?
+    case $exitcode in
+	0) NAME=$expanded_name
+	    BRANCH=$PREFIX$NAME
+	    ;;
+	*) exit 1 ;;
+    esac
 }
 
-require_no_existing_issue_branches() {
-    local issue_branches=$(echo "$(git_local_branches)" | grep "^$PREFIX")
-    local first_branch=$(echo ${issue_branches} | head -n1)
-    first_branch=${first_branch#$PREFIX}
-    [ -z "$issue_branches" ] || \
-	die "There is an existing issue branch ($first_branch). Finish that one first."
+require_base_is_on_develop() {
+    if ! git branch --no-color --contains "$BASE" 2>/dev/null \
+	| sed 's/[* ] //g' \
+	| grep -q "^$DEVELOP_BRANCH\$"; then
+	die "fatal: Given base '$BASE' is not a valid commit on '$DEVELOP_BRANCH'."
+    fi
 }
 
 cmd_start() {
     DEFINE_boolean fetch false "fetch from $ORIGIN before performing finish" F
     parse_args "$@"
-    BASE=${2:-$MASTER_BRANCH}
-    require_version_arg
-    require_base_is_on_master
-    require_no_existing_issue_branches
-    
+    BASE=${2:-$DEVELOP_BRANCH}
+    require_name_arg
+    require_base_is_on_develop
+
     # sanity checks
     require_clean_working_tree
     require_branch_absent "$BRANCH"
-    require_tag_absent "$VERSION_PREFIX$VERSION"
+
+    # update the local repo with remote changes, if asked
     if flag fetch; then
-	git_do fetch -q "$ORIGIN" "$MASTER_BRANCH"
+	git_do fetch -q "$ORIGIN" "$DEVELOP_BRANCH"
     fi
-    if has "$ORIGIN/$MASTER_BRANCH" $(git_remote_branches); then
-	require_branches_equal "$MASTER_BRANCH" "$ORIGIN/$MASTER_BRANCH"
+
+    # if the origin branch counterpart exists, assert that the local branch
+    # isn't behind it (to avoid unnecessary rebasing)
+    if git_branch_exists "$ORIGIN/$DEVELOP_BRANCH"; then
+	require_branches_equal "$DEVELOP_BRANCH" "$ORIGIN/$DEVELOP_BRANCH"
     fi
-    
+
     # create branch
-    git_do checkout -b "$BRANCH" "$BASE"
-    
+    if ! git_do checkout -b "$BRANCH" "$BASE"; then
+	die "Could not create issue branch '$BRANCH'"
+    fi
+
     echo
     echo "Summary of actions:"
     echo "- A new branch '$BRANCH' was created, based on '$BASE'"
     echo "- You are now on branch '$BRANCH'"
     echo
     echo "Follow-up actions:"
-    echo "- Bump the version number now!"
-    echo "- Start committing your hot fixes"
-    echo "- When done, run:"
-    echo
-    echo "     git flow issue finish '$VERSION'"
+    echo "- Start committing on your issue."
+    echo "- To publish your changes for testing:"
+    echo "     git flow issue publish '$NAME'"
+    echo "- When done, use:"
+    echo "     git flow issue finish '$NAME'"
     echo
 }
 
 cmd_publish() {
     parse_args "$@"
-    require_version_arg
+    require_name_arg
     
     # sanity checks
     require_clean_working_tree
@@ -222,7 +244,7 @@ cmd_publish() {
 
 cmd_track() {
     parse_args "$@"
-    require_version_arg
+    require_name_arg
     
     # sanity checks
     require_clean_working_tree
@@ -242,109 +264,181 @@ cmd_track() {
 
 cmd_finish() {
     DEFINE_boolean fetch false "fetch from $ORIGIN before performing finish" F
-    DEFINE_boolean sign false "sign the release tag cryptographically" s
-    DEFINE_string signingkey "" "use the given GPG-key for the digital signature (implies -s)" u
-    DEFINE_string message "" "use the given tag message" m
-    DEFINE_string messagefile "" "use the contents of the given file as tag message" f
-    DEFINE_boolean push false "push to $ORIGIN after performing finish" p
+    DEFINE_boolean rebase false "rebase instead of merge" r
     DEFINE_boolean keep false "keep branch after performing finish" k
-    DEFINE_boolean notag false "don't tag this release" n
+    DEFINE_boolean force_delete false "force delete issue branch after finish" D
+    DEFINE_boolean squash false "squash issue during merge" S
     parse_args "$@"
-    require_version_arg
-    
-    # handle flags that imply other flags
-    if [ "$FLAGS_signingkey" != "" ]; then
-	FLAGS_sign=$FLAGS_TRUE
-    fi
-    
+    expand_nameprefix_arg
+
     # sanity checks
     require_branch "$BRANCH"
-    require_clean_working_tree
-    if flag fetch; then
-	git_do fetch -q "$ORIGIN" "$MASTER_BRANCH" || \
-	    die "Could not fetch $MASTER_BRANCH from $ORIGIN."
-	git_do fetch -q "$ORIGIN" "$DEVELOP_BRANCH" || \
-	    die "Could not fetch $DEVELOP_BRANCH from $ORIGIN."
+
+    # detect if we're restoring from a merge conflict
+    if [ -f "$DOT_GIT_DIR/.gitflow/MERGE_BASE" ]; then
+	#
+        # TODO: detect that we're working on the correct branch here!
+	# The user need not necessarily have given the same $NAME twice here
+	# (although he/she should).
+	# 
+
+	# TODO: git_is_clean_working_tree() should provide an alternative
+	# exit code for "unmerged changes in working tree", which we should
+	# actually be testing for here
+	if git_is_clean_working_tree; then
+	    FINISH_BASE=$(cat "$DOT_GIT_DIR/.gitflow/MERGE_BASE")
+
+		# Since the working tree is now clean, either the user did a
+		# succesfull merge manually, or the merge was cancelled.
+		# We detect this using git_is_branch_merged_into()
+		if git_is_branch_merged_into "$BRANCH" "$FINISH_BASE"; then
+			rm -f "$DOT_GIT_DIR/.gitflow/MERGE_BASE"
+			helper_finish_cleanup
+			exit 0
+		else
+			# If the user cancelled the merge and decided to wait until later,
+			# that's fine. But we have to acknowledge this by removing the
+			# MERGE_BASE file and continuing normal execution of the finish
+			rm -f "$DOT_GIT_DIR/.gitflow/MERGE_BASE"
+		fi
+	else
+	    echo
+	    echo "Merge conflicts not resolved yet, use:"
+	    echo "    git mergetool"
+	    echo "    git commit"
+	    echo 
+	    echo "You can then complete the finish by running it again:"
+	    echo "    git flow issue finish $NAME"
+	    echo
+	    exit 1
+	fi
     fi
-    if has "$ORIGIN/$MASTER_BRANCH" $(git_remote_branches); then
-	require_branches_equal "$MASTER_BRANCH" "$ORIGIN/$MASTER_BRANCH"
+
+    # sanity checks
+    require_clean_working_tree
+
+    # update local repo with remote changes first, if asked
+    if has "$ORIGIN/$BRANCH" $(git_remote_branches); then
+	if flag fetch; then
+	    git_do fetch -q "$ORIGIN" "$BRANCH"
+	    git_do fetch -q "$ORIGIN" "$DEVELOP_BRANCH"
+	fi
+    fi
+    
+    if has "$ORIGIN/$BRANCH" $(git_remote_branches); then
+	require_branches_equal "$BRANCH" "$ORIGIN/$BRANCH"
     fi
     if has "$ORIGIN/$DEVELOP_BRANCH" $(git_remote_branches); then
 	require_branches_equal "$DEVELOP_BRANCH" "$ORIGIN/$DEVELOP_BRANCH"
     fi
     
-    # try to merge into master
-    # in case a previous attempt to finish this release branch has failed,
-    # but the merge into master was successful, we skip it now
-    if ! git_is_branch_merged_into "$BRANCH" "$MASTER_BRANCH"; then
-	git_do checkout "$MASTER_BRANCH" || \
-	    die "Could not check out $MASTER_BRANCH."
-	git_do merge --no-ff "$BRANCH" || \
-	    die "There were merge conflicts."
-	    # TODO: What do we do now?
-    fi
-
-    if noflag notag; then
-	# try to tag the release
-	# in case a previous attempt to finish this release branch has failed,
-	# but the tag was set successful, we skip it now
-	local tagname=$VERSION_PREFIX$VERSION
-	if ! git_tag_exists "$tagname"; then
-	    local opts="-a"
-	    flag sign && opts="$opts -s"
-	    [ "$FLAGS_signingkey" != "" ] && opts="$opts -u '$FLAGS_signingkey'"
-	    [ "$FLAGS_message" != "" ] && opts="$opts -m '$FLAGS_message'"
-	    [ "$FLAGS_messagefile" != "" ] && opts="$opts -F '$FLAGS_messagefile'"
-	    eval git_do tag $opts "$VERSION_PREFIX$VERSION" "$BRANCH" || \
-		die "Tagging failed. Please run finish again to retry."
+    # merge into BASE
+    git_do checkout "$DEVELOP_BRANCH"
+    if [ "$(git rev-list -n2 "$DEVELOP_BRANCH..$BRANCH" | wc -l)" -eq 1 ]; then
+	git_do merge --ff "$BRANCH"
+    else
+	if noflag squash; then
+	    git_do merge --no-ff "$BRANCH"
+	else
+	    git_do merge --squash "$BRANCH"
+	    git_do commit
+	    git_do merge "$BRANCH"
 	fi
     fi
     
-    # try to merge into develop
-    # in case a previous attempt to finish this release branch has failed,
-    # but the merge into develop was successful, we skip it now
-    if ! git_is_branch_merged_into "$BRANCH" "$DEVELOP_BRANCH"; then
-	git_do checkout "$DEVELOP_BRANCH" || \
-	    die "Could not check out $DEVELOP_BRANCH."
-        
-	# TODO: Actually, accounting for 'git describe' pays, so we should
-	# ideally git merge --no-ff $tagname here, instead!
-	git_do merge --no-ff "$BRANCH" || \
-	    die "There were merge conflicts."
-	     # TODO: What do we do now?
+    if [ $? -ne 0 ]; then
+	# oops.. we have a merge conflict!
+	# write the given $DEVELOP_BRANCH to a temporary file (we need it later)
+	mkdir -p "$DOT_GIT_DIR/.gitflow"
+	echo "$DEVELOP_BRANCH" > "$DOT_GIT_DIR/.gitflow/MERGE_BASE"
+	echo
+	echo "There were merge conflicts. To resolve the merge conflict manually, use:"
+	echo "    git mergetool"
+	echo "    git commit"
+	echo 
+	echo "You can then complete the finish by running it again:"
+	echo "    git flow issue finish $NAME"
+	echo
+	exit 1
     fi
+    
+    # when no merge conflict is detected, just clean up the issue branch
+    helper_finish_cleanup
+}
+
+helper_finish_cleanup() {
+    # sanity checks
+    require_branch "$BRANCH"
+    require_clean_working_tree
     
     # delete branch
-    if noflag keep; then
-	git_do branch -d "$BRANCH"
+    if flag fetch; then
+	git_do push "$ORIGIN" ":refs/heads/$BRANCH"
     fi
-    
-    if flag push; then
-	git_do push "$ORIGIN" "$DEVELOP_BRANCH" || \
-	    die "Could not push to $DEVELOP_BRANCH from $ORIGIN."
-	git_do push "$ORIGIN" "$MASTER_BRANCH" || \
-	    die "Could not push to $MASTER_BRANCH from $ORIGIN."
-	if noflag notag; then
-	    git_do push --tags "$ORIGIN" || \
-		die "Could not push tags to $ORIGIN."
+	
+    if noflag keep; then
+	if flag force_delete; then
+	    git_do branch -D "$BRANCH"
+	else
+	    git_do branch -d "$BRANCH"
 	fi
     fi
-    
+
     echo
     echo "Summary of actions:"
-    echo "- Latest objects have been fetched from '$ORIGIN'"
-    echo "- Issue branch has been merged into '$MASTER_BRANCH'"
-    if noflag notag; then
-	echo "- The issue was tagged '$VERSION_PREFIX$VERSION'"
-	fi
-    echo "- Issue branch has been back-merged into '$DEVELOP_BRANCH'"
+    echo "- The issue branch '$BRANCH' was merged into '$DEVELOP_BRANCH'"
     if flag keep; then
 	echo "- Issue branch '$BRANCH' is still available"
     else
-	echo "- Issue branch '$BRANCH' has been deleted"
+	echo "- Issue branch '$BRANCH' has been removed"
     fi
-    if flag push; then
-	echo "- '$DEVELOP_BRANCH', '$MASTER_BRANCH' and tags have been pushed to '$ORIGIN'"
-    fi
+    echo "- You are now on branch '$DEVELOP_BRANCH'"
     echo
+}
+
+cmd_pull() {
+    #DEFINE_string prefix false 'alternative remote issue branch name prefix' p
+    DEFINE_boolean rebase false "pull with rebase" r
+    parse_remote_name "$@"
+
+    if [ -z "$REMOTE" ]; then
+	die "Name a remote explicitly."
+    fi
+    name_or_current
+
+    # To avoid accidentally merging different issue branches into each other,
+    # die if the current issue branch differs from the requested $NAME
+    # argument.
+    local current_branch=$(git_current_branch)
+    if startswith "$current_branch" "$PREFIX"; then
+	# we are on a local issue branch already, so $BRANCH must be equal to
+	# the current branch
+	avoid_accidental_cross_branch_action || die
+    fi
+
+    require_clean_working_tree
+    
+    if git_branch_exists "$BRANCH"; then
+	# Again, avoid accidental merges
+	avoid_accidental_cross_branch_action || die
+
+	# we already have a local branch called like this, so simply pull the
+	# remote changes in
+	if flag rebase; then
+	    if ! git_do pull --rebase -q "$REMOTE" "$BRANCH"; then
+		warn "Pull was aborted. There might be conflicts during rebase or '$REMOTE' might be inaccessible."
+		exit 1
+	    fi
+	else
+	    git_do pull -q "$REMOTE" "$BRANCH" || die "Failed to pull from remote '$REMOTE'."
+	fi
+        
+	echo "Pulled $REMOTE's changes into $BRANCH."
+    else
+	# setup the local branch clone for the first time
+	git_do fetch -q "$REMOTE" "$BRANCH" || die "Fetch failed."     # stores in FETCH_HEAD
+	git_do branch --no-track "$BRANCH" FETCH_HEAD || die "Branch failed."
+	git_do checkout -q "$BRANCH" || die "Checking out new local branch failed."
+	echo "Created local branch $BRANCH based on $REMOTE's $BRANCH."
+    fi
 }
