Make function require_name_arg a common function.
Instead of defining the same function in multiple scripts, we created a
new common function gitflow_require_name_arg

diff --git a/gitflow-common b/gitflow-common
--- a/gitflow-common
+++ b/gitflow-common
@@ -180,6 +180,15 @@ gitflow_require_version_arg() {
 		exit 1
 	fi
 }
+
+gitflow_require_name_arg() {
+	if [ "$NAME" = "" ]; then
+		warn "Missing argument <name>"
+		usage
+		exit 1
+	fi
+}
+
 # Check if this repo has been inited for gitflow
 gitflow_has_master_configured() {
 	local master=$(git config --get gitflow.branch.master)
