Make function require_version_arg a common function.
Instead of defining the same function in multiple scripts, we created a
new common function gitflow_require_version_arg

diff --git a/gitflow-common b/gitflow-common
--- a/gitflow-common
+++ b/gitflow-common
@@ -173,6 +173,13 @@ git_is_ancestor() {
 # gitflow specific common functionality
 #
 
+gitflow_require_version_arg() {
+	if [ "$VERSION" = "" ]; then
+		warn "Missing argument <version>"
+		usage
+		exit 1
+	fi
+}
 # Check if this repo has been inited for gitflow
 gitflow_has_master_configured() {
 	local master=$(git config --get gitflow.branch.master)
