Remove porcelain commands, rewrite some code.
This will increase the speed up of the scripts and we don't have to
worry about changes in the layout of the output of the porcelain
commands.

diff --git a/gitflow-common b/gitflow-common
--- a/gitflow-common
+++ b/gitflow-common
@@ -69,23 +69,34 @@ noflag() { local FLAG; eval FLAG='$FLAGS_'$1; [ $FLAG -ne $FLAGS_TRUE ]; }
 # Git specific common functionality
 #
 
-git_local_branches() { git branch --no-color | sed 's/^[* ] //'; }
-git_remote_branches() { git branch -r --no-color | sed 's/^[* ] //'; }
-git_all_branches() { ( git branch --no-color; git branch -r --no-color) | sed 's/^[* ] //'; }
-git_all_tags() { git tag; }
+git_local_branches() { git for-each-ref --format='%(refname:short)' refs/heads; }
+git_remote_branches() { git for-each-ref --format='%(refname:short)' refs/remotes; }
+git_all_branches() { git for-each-ref --format='%(refname:short)' refs/remotes refs/heads; }
+git_all_tags() { git for-each-ref --format='%(refname:short)' refs/tags; }
 
 git_current_branch() {
-	git branch --no-color | grep '^\* ' | grep -v 'no branch' | sed 's/^* //g'
+	local branch_name="$(git symbolic-ref --short --quiet HEAD)" || branch_name="(unnamed branch)"     # detached HEAD
+	echo "$branch_name"
 }
 
 git_is_clean_working_tree() {
-	if ! git diff --no-ext-diff --ignore-submodules --quiet --exit-code; then
-		return 1
-	elif ! git diff-index --cached --quiet --ignore-submodules HEAD --; then
-		return 2
-	else
-		return 0
+	git rev-parse --verify HEAD >/dev/null || exit 1
+	git update-index -q --ignore-submodules --refresh
+	local err=0
+
+	# Check for unstaged changes
+	if ! git diff-files --quiet --ignore-submodules
+	then
+		err=1
 	fi
+
+	# Check for Uncommited changes
+	if ! git diff-index --cached --quiet --ignore-submodules HEAD --
+	then
+		err=2
+	fi
+
+	return $err
 }
 
 git_repo_is_headless() {
@@ -93,19 +104,19 @@ git_repo_is_headless() {
 }
 
 git_local_branch_exists() {
-	has $1 $(git_local_branches)
+	[ -n "$(git for-each-ref --format='%(refname:short)' refs/heads/$1)" ]
 }
 
 git_remote_branch_exists() {
-	has $1 $(git_remote_branches)
+	[ -n "$(git for-each-ref --format='%(refname:short)' refs/remotes/$1)" ]
 }
 
 git_branch_exists() {
-	has $1 $(git_all_branches)
+	git_local_branch_exists "$1" || git_remote_branch_exists "$1"
 }
 
 git_tag_exists() {
-	has $1 $(git_all_tags)
+	[ -n "$(git for-each-ref --format='%(refname:short)' refs/tags/$1)" ]
 }
 
 #
@@ -145,10 +156,11 @@ git_compare_branches() {
 # Checks whether branch $1 is succesfully merged into $2
 #
 git_is_branch_merged_into() {
-	local subject=$1
-	local base=$2
-	local all_merges="$(git branch --no-color --contains $subject | sed 's/^[* ] //')"
-	has $base $all_merges
+	local merge_hash=$(git merge-base $1 $2)
+	local base_hash=$(git rev-parse $1)
+
+	# If the hashes are equal, the branches are merged.
+	[ "$merge_hash" = "$base_hash" ]
 }
 
 #
@@ -177,8 +189,7 @@ gitflow_has_prefixes_configured() {
 gitflow_is_initialized() {
 	gitflow_has_master_configured                    && \
 	gitflow_has_develop_configured                   && \
-	[ "$(git config --get gitflow.branch.master)" !=    \
-	  "$(git config --get gitflow.branch.develop)" ] && \
+	[ "$(git config --get gitflow.branch.master)" != "$(git config --get gitflow.branch.develop)" ] && \
 	gitflow_has_prefixes_configured
 }
 
@@ -245,7 +256,7 @@ gitflow_resolve_nameprefix() {
 #
 
 require_git_repo() {
-	if ! git rev-parse --git-dir >/dev/null 2>&1; then
+	if ! git rev-parse --git-dir 2>/dev/null; then
 		die "fatal: Not a git repository"
 	fi
 }
@@ -268,35 +279,23 @@ require_clean_working_tree() {
 }
 
 require_local_branch() {
-	if ! git_local_branch_exists $1; then
-		die "fatal: Local branch '$1' does not exist and is required."
-	fi
+	git_local_branch_exists $1 || die "fatal: Local branch '$1' does not exist and is required."
 }
 
 require_remote_branch() {
-	if ! has $1 $(git_remote_branches); then
-		die "Remote branch '$1' does not exist and is required."
-	fi
+	git_remote_branch_exists $1 || die "Remote branch '$1' does not exist and is required."
 }
 
 require_branch() {
-	if ! has $1 $(git_all_branches); then
-		die "Branch '$1' does not exist and is required."
-	fi
+	git_branch_exists || die "Branch '$1' does not exist and is required."
 }
 
 require_branch_absent() {
-	if has $1 $(git_all_branches); then
-		die "Branch '$1' already exists. Pick another name."
-	fi
+	git_branch_exists $1 &&	die "Branch '$1' already exists. Pick another name."
 }
 
 require_tag_absent() {
-	for tag in $(git_all_tags); do
-		if [ "$1" = "$tag" ]; then
-			die "Tag '$1' already exists. Pick another name."
-		fi
-	done
+	git_tag_exists "$1" && die "Tag '$1' already exists. Pick another name."
 }
 
 require_branches_equal() {
